# Generated by Django 3.2.9 on 2021-11-30 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='スポーツ名')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='sports/images', verbose_name='カバー写真')),
                ('rule', models.TextField(verbose_name='ルール')),
            ],
            options={
                'verbose_name': 'Sports',
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='選手名')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='sports/images/profile', verbose_name='プロフィール写真')),
                ('description', models.TextField(verbose_name='選手説明')),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sports', verbose_name='スポーツ名')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='関連記事')),
                ('sports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sports', verbose_name='スポーツ')),
            ],
        ),
    ]
